{
 "title": "Alerts Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pending Alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"pending\"})"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"})"
    }
   ]
  },
  { "title": "Alerts List", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Instances States",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ALERTS{alertname=\"InstanceDown\",alertstate=~\"firing|pending\"}"
    }
   ]
  }
 ]
}