{
 "title": "Monitoring of toxicity application",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node_exporter\", instance=\"node_exporter:9100\"} - node_filesystem_avail_bytes{job=\"node_exporter\", instance=\"node_exporter:9100\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_virtual_memory_bytes[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(cpu)(irate(node_cpu_seconds_total{job=\"node_exporter\", instance=\"node_exporter:9100\", mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  }
 ]
}